name: 'gi-data'
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python >= 3
  - pip
  - snakemake >= 5.6
  - pytest
  - twine
  - click
  - numpy
  - pandas
  - xlrd # excel reader
  - cloudpickle
  - jupyter
  - tqdm
  - pip:
    - chacon
